[package]
name = "hibiki"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = { version = "0.9.1", features = ["gtk4"] }
env_logger = "0.11.5"
gstreamer = "0.23.0"
gtk4 = "0.9.0"
libadwaita = "0.7.0"
log = "0.4.22"
